### ISSUE TITLE
Measurand data items should be allowed appended SU in examples

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/dictionary_check_action#3]
Currently a validation issue arises if `_description_example.case` has an appended SU for `_type.contents` 'Real' and `_type.purpose` Measurand. I suggest that this is too strict, and that an appended SU should be allowed, or at least an option should be provided to allow this not to raise an error.

**Comment by jcbollinger** [comment]
The definition for _type.purpose value 'Measurand'<https://www.iucr.org/__data/iucr/cifdic_html/3/DDL_DIC/Itype.purpose.html> explicitly specifies that items with that purpose afford lexical values with appended SUs.  In principle, this applies most naturally to items having _type.contents 'Real', but the current dictionary does not appear to limit it to such items.

I agree, therefore, that the validator is itself in error when it flags measurand values with appended SUs, and especially so for measurand items having content type Real.  Adding an option to disable that behavior is the minimum appropriate mitigation, but if such an option were added then I would suggest that it default to allowing appended SUs, as that is, after all, what DDLm specifies.


John
________________________________
From: jamesrhester ***@***.***>
Sent: Thursday, May 6, 2021 11:23 PM
To: COMCIFS/dictionary_check_action ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [COMCIFS/dictionary_check_action] Measurand data items should be allowed appended SU in examples (#3)

Caution: External Sender. Do not open unless you know the content is safe.


Currently a validation issue arises if _description_example.case has an appended SU for _type.contents 'Real' and _type.purpose Measurand. I suggest that this is too strict, and that an appended SU should be allowed, or at least an option should be provided to allow this not to raise an error.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCOMCIFS%2Fdictionary_check_action%2Fissues%2F3&data=04%7C01%7CJohn.Bollinger%40StJude.org%7C3bcd1b8eb4c749d8fb0008d9110fe989%7C22340fa892264871b677d3b3e377af72%7C0%7C0%7C637559582312967244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g19FKjKkkzLtJMQ%2BNvUh3qsr%2BwhtIfqE74auj9XWNk8%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA4A7UN4XBOGZLZY2UBD6BTTMNTNJANCNFSM44I3UWYA&data=04%7C01%7CJohn.Bollinger%40StJude.org%7C3bcd1b8eb4c749d8fb0008d9110fe989%7C22340fa892264871b677d3b3e377af72%7C0%7C0%7C637559582312967244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yCeVz2Cs9ElZxQUZXFBSey7uaaXh6Wcear8jSeGJ5yQ%3D&reserved=0>.

________________________________

Email Disclaimer: www.stjude.org/emaildisclaimer
Consultation Disclaimer: www.stjude.org/consultationdisclaimer

**Comment by jamesrhester** [comment]
Upon studying the code, I realised that there is a facility to simply ignore certain messages, so I have used that to exclude any errors involving the value of `_description_example.case`. Please see pull request #4 and approve/improve.

**Comment by vaitkus** [comment]
The issue was further resolved by updating the validator to allow appended SU in `_description_example.case` attribute values if the attribute appear in the definition of a Measurand data item. This fix was introduced by merging PR #8.
